"""warehouse: run identity, read model, decisions, outbox

Revision ID: 7907d04c69bc
Revises:
Create Date: 2026-09-26 09:49:44.286920

Generated by ``alembic revision --autogenerate`` and then read by a human: the
constraints this schema depends on (money as ``bigint``, ``run_id`` as
``char(26)``, the immutability trigger) are the parts autogenerate cannot infer
from type annotations alone.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7907d04c69bc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_source",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("retrieval", sa.Text(), nullable=False),
        sa.Column("license", sa.String(length=64), nullable=False),
        sa.Column("license_obligation", sa.Text(), nullable=False),
        sa.Column("citation", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("label_caveat", sa.Text(), nullable=False),
        sa.Column("known_biases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("synthetic_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ingest_allowed", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("retrieved_at", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "erasure_request",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subject_ref_hash", sa.String(length=64), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("mapping_rows_deleted", sa.Integer(), nullable=False),
        sa.Column("audit_seq", sa.Integer(), nullable=True),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "measurement",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column(
            "measured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "name", name="uq_measurement_scope_name"),
    )
    op.create_table(
        "policy",
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("capacity_minutes", sa.Integer(), nullable=False),
        sa.Column("recovery_rate", sa.Double(), nullable=False),
        sa.Column(
            "recovery_sensitivity_band", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("analyst_cost_per_hour_minor", sa.BigInteger(), nullable=False),
        sa.Column("min_review_minutes", sa.Double(), nullable=False),
        sa.Column("friction_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("four_eyes_threshold_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "review_minutes_by_band", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("solver", sa.String(length=16), nullable=False),
        sa.Column("degraded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("degraded_reason", sa.Text(), nullable=True),
        sa.Column("solve_ms", sa.Integer(), nullable=True),
        sa.Column("optimality_gap_minor", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("min_review_minutes > 0", name="ck_policy_positive_review_minutes"),
        sa.CheckConstraint(
            "recovery_rate > 0 AND recovery_rate < 1", name="ck_policy_recovery_bounds"
        ),
        sa.PrimaryKeyConstraint("policy_id"),
    )
    op.create_table(
        "pseudonym_map",
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("salt_version", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account_key"),
    )
    op.create_table(
        "run",
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.String(length=24), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("dataset_ref", sa.String(length=128), nullable=True),
        sa.Column("source_revision", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("superseded_by", sa.CHAR(length=26), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("artifact_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "state IN ('running', 'complete', 'failed', 'superseded')", name="ck_run_state"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "ablation_row",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("variant", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("corpus", sa.String(length=64), nullable=False),
        sa.Column("pr_auc", sa.Double(), nullable=False),
        sa.Column("net_benefit_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("ci_low", sa.Double(), nullable=False),
        sa.Column("ci_high", sa.Double(), nullable=False),
        sa.Column("ci_method", sa.String(length=64), nullable=False),
        sa.Column("n_resamples", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "variant", "corpus", name="uq_ablation_row"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("source_dataset", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("txn_count", sa.Integer(), nullable=False),
        sa.Column("n_outbound", sa.Integer(), nullable=False),
        sa.Column("n_inbound", sa.Integer(), nullable=False),
        sa.Column("n_counterparties", sa.Integer(), nullable=False),
        sa.Column("funding_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("age_days", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", name="uq_account_run_key"),
    )
    op.create_index(
        "ix_account_run_first_seen", "account", ["run_id", "first_seen_at"], unique=False
    )
    op.create_table(
        "account_membership",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("degree", sa.Integer(), nullable=False),
        sa.Column("pagerank", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", name="uq_membership_run_key"),
    )
    op.create_table(
        "audit_event",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("chain_seq", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
        sa.UniqueConstraint("chain_seq", name="uq_audit_event_chain_seq"),
    )
    op.create_index(
        "ix_audit_event_subject_seq", "audit_event", ["subject", "chain_seq"], unique=False
    )
    op.create_table(
        "backtest_fold",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("fold_index", sa.Integer(), nullable=False),
        sa.Column("corpus", sa.String(length=64), nullable=False),
        sa.Column("train_start", sa.Date(), nullable=False),
        sa.Column("train_end", sa.Date(), nullable=False),
        sa.Column("embargo_days", sa.Integer(), nullable=False),
        sa.Column("embargo_end", sa.Date(), nullable=False),
        sa.Column("test_start", sa.Date(), nullable=False),
        sa.Column("test_end", sa.Date(), nullable=False),
        sa.Column("n_train", sa.Integer(), nullable=False),
        sa.Column("n_test", sa.Integer(), nullable=False),
        sa.Column("pr_auc", sa.Double(), nullable=False),
        sa.Column("auroc", sa.Double(), nullable=False),
        sa.Column("brier", sa.Double(), nullable=False),
        sa.Column("precision_at_budget", sa.Double(), nullable=True),
        sa.Column("recall_at_budget", sa.Double(), nullable=True),
        sa.Column("precision_undefined", sa.Boolean(), nullable=False),
        sa.Column("alerts", sa.Integer(), nullable=False),
        sa.Column("captured_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_benefit_minor", sa.BigInteger(), nullable=False),
        sa.Column("max_drawdown_minor", sa.BigInteger(), nullable=False),
        sa.Column("var95_minor", sa.BigInteger(), nullable=False),
        sa.Column("es975_minor", sa.BigInteger(), nullable=False),
        sa.Column("mc_runs", sa.Integer(), nullable=False),
        sa.Column("mc_seed", sa.Integer(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("entity_disjoint", sa.Boolean(), nullable=False),
        sa.Column("test_fold_touched_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "fold_index", name="uq_backtest_fold"),
    )
    op.create_table(
        "band_definition",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("band", sa.CHAR(length=1), nullable=False),
        sa.Column("lower_points", sa.Integer(), nullable=False),
        sa.Column("upper_points", sa.Integer(), nullable=True),
        sa.Column("observed_rate", sa.Double(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("review_minutes", sa.Double(), nullable=False),
        sa.CheckConstraint("band IN ('A','B','C','D','E')", name="ck_band_definition_band"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "band", name="uq_band_definition"),
    )
    op.create_table(
        "batch",
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("declared_rows", sa.Integer(), nullable=False),
        sa.Column("actual_rows", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("batch_id"),
    )
    op.create_table(
        "community",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("canonical_index", sa.Integer(), nullable=False),
        sa.Column("raw_label", sa.String(length=32), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("density", sa.Double(), nullable=True),
        sa.Column("total_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=True),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "canonical_index", name="uq_community_run_index"),
    )
    op.create_table(
        "confusion_cell",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("prediction", sa.String(length=16), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "label", "prediction", name="uq_confusion_cell"),
    )
    op.create_table(
        "curve_point",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.Column("point_index", sa.Integer(), nullable=False),
        sa.Column("x", sa.Double(), nullable=False),
        sa.Column("y", sa.Double(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("operating_point", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=True),
        sa.CheckConstraint(
            "family IN ('reliability','pr_curve','shap_global','typology_recall','per_typology_precision')",
            name="ck_curve_point_family",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "family", "point_index", name="uq_curve_point"),
    )
    op.create_table(
        "dataset_file",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("file_name", sa.String(length=256), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dataset_source.source_id"],
        ),
        sa.PrimaryKeyConstraint("source_id", "file_name"),
    )
    op.create_table(
        "drift_period",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("attribute", sa.String(length=128), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("psi", sa.Double(), nullable=False),
        sa.Column("csi", sa.Double(), nullable=True),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("bad_rate", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "attribute", "period", name="uq_drift_period"),
    )
    op.create_table(
        "economics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("exposure_minor", sa.BigInteger(), nullable=False),
        sa.Column("expected_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("loss_avoided_minor", sa.BigInteger(), nullable=False),
        sa.Column("analyst_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("friction_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("analyst_minutes", sa.Double(), nullable=False),
        sa.Column("recovery_rate", sa.Double(), nullable=False),
        sa.Column("ev_density", sa.Double(), nullable=True),
        sa.Column("mc_runs", sa.Integer(), nullable=False),
        sa.Column("mc_seed", sa.Integer(), nullable=False),
        sa.Column("mc_p05_minor", sa.BigInteger(), nullable=False),
        sa.Column("mc_p50_minor", sa.BigInteger(), nullable=False),
        sa.Column("mc_p95_minor", sa.BigInteger(), nullable=False),
        sa.Column("mc_interval", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name="ck_economics_currency"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", name="uq_economics_run_key"),
    )
    op.create_index(
        "ix_economics_run_exposure",
        "economics",
        ["run_id", sa.text("exposure_minor DESC")],
        unique=False,
    )
    op.create_table(
        "evidence_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("txn_id", sa.String(length=64), nullable=True),
        sa.Column("rule_id", sa.String(length=16), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_evidence_run_key_ts",
        "evidence_event",
        ["run_id", "account_key", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "fairness_row",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("axis", sa.String(length=64), nullable=False),
        sa.Column("axis_rationale", sa.Text(), nullable=False),
        sa.Column("bucket", sa.String(length=64), nullable=False),
        sa.Column("fp_rate", sa.Double(), nullable=False),
        sa.Column("fn_rate", sa.Double(), nullable=True),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "axis", "bucket", name="uq_fairness_row"),
    )
    op.create_table(
        "graph_edge",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("src_account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("dst_account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("txn_count", sa.Integer(), nullable=False),
        sa.Column("total_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("first_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_rail", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "src_account_key", "dst_account_key", name="uq_graph_edge"),
    )
    op.create_index("ix_graph_edge_dst", "graph_edge", ["run_id", "dst_account_key"], unique=False)
    op.create_index("ix_graph_edge_src", "graph_edge", ["run_id", "src_account_key"], unique=False)
    op.create_table(
        "job_run",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=True),
        sa.Column("queue", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index("ix_job_run_kind_created", "job_run", ["kind", "created_at"], unique=False)
    op.create_table(
        "model_disagreement",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("band_scorecard", sa.CHAR(length=1), nullable=False),
        sa.Column("band_gbm", sa.CHAR(length=1), nullable=False),
        sa.Column("p_scorecard", sa.Double(), nullable=False),
        sa.Column("p_gbm", sa.Double(), nullable=False),
        sa.Column("delta", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", name="uq_model_disagreement"),
    )
    op.create_table(
        "perturbation_row",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("magnitude", sa.Double(), nullable=False),
        sa.Column("result", sa.Double(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "kind", name="uq_perturbation_row"),
    )
    op.create_table(
        "policy_allocation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("beyond_capacity", sa.Boolean(), nullable=False),
        sa.Column("expected_value_minor", sa.BigInteger(), nullable=False),
        sa.Column("exposure_minor", sa.BigInteger(), nullable=False),
        sa.Column("analyst_minutes", sa.Double(), nullable=False),
        sa.Column("ev_density", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.policy_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "policy_id", "account_key", name="uq_policy_allocation"),
    )
    op.create_index(
        "ix_allocation_run_policy_rank",
        "policy_allocation",
        ["run_id", "policy_id", "rank"],
        unique=False,
    )
    op.create_table(
        "policy_simulation",
        sa.Column("simulation_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("base_policy_id", sa.String(length=64), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entered", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("left", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("degraded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("degraded_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_policy_id"],
            ["policy.policy_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("simulation_id"),
    )
    op.create_table(
        "policy_summary",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("capacity_minutes", sa.Integer(), nullable=False),
        sa.Column("selected_count", sa.Integer(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("loss_avoided_minor", sa.BigInteger(), nullable=False),
        sa.Column("analyst_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("friction_cost_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_benefit_minor", sa.BigInteger(), nullable=False),
        sa.Column("benefit_per_analyst_hour_minor", sa.BigInteger(), nullable=False),
        sa.Column("max_drawdown_minor", sa.BigInteger(), nullable=False),
        sa.Column("zero_drawdown", sa.Boolean(), nullable=False),
        sa.Column("var_alpha", sa.Double(), nullable=False),
        sa.Column("var95_minor", sa.BigInteger(), nullable=False),
        sa.Column("es_alpha", sa.Double(), nullable=False),
        sa.Column("es975_minor", sa.BigInteger(), nullable=False),
        sa.Column("mc_runs", sa.Integer(), nullable=False),
        sa.Column("mc_seed", sa.Integer(), nullable=False),
        sa.Column("alerts_per_10k_accounts", sa.Double(), nullable=False),
        sa.Column("risk_adjusted_benefit", sa.Double(), nullable=False),
        sa.Column("risk_adjusted_benefit_note", sa.Text(), nullable=False),
        sa.Column("cumulative_curve", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("frontier", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("baselines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.policy_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "policy_id", name="uq_policy_summary"),
    )
    op.create_table(
        "quarantine_row",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=True),
        sa.Column("batch_id", sa.String(length=64), nullable=True),
        sa.Column("source_dataset", sa.String(length=64), nullable=False),
        sa.Column("failing_constraint", sa.String(length=128), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("original_row", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "quarantined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_quarantine_run_id", "quarantine_row", ["run_id"], unique=False)
    op.create_table(
        "rating_migration",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("from_band", sa.CHAR(length=1), nullable=False),
        sa.Column("to_band", sa.CHAR(length=1), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "from_band", "to_band", name="uq_rating_migration"),
    )
    op.create_table(
        "review_case",
        sa.Column("case_id", sa.CHAR(length=26), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("status", sa.String(length=24), server_default=sa.text("'open'"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "current_decision_seq", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'pending_four_eyes', 'decided', 'reversed')", name="ck_case_status"
        ),
        sa.CheckConstraint("version >= 1", name="ck_case_version_positive"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("case_id"),
        sa.UniqueConstraint("run_id", "account_key", name="uq_case_run_key"),
    )
    op.create_table(
        "rule_hit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("rule_id", sa.String(length=16), nullable=False),
        sa.Column("rule_name", sa.String(length=128), nullable=False),
        sa.Column("typology", sa.String(length=64), nullable=False),
        sa.Column("fired", sa.Boolean(), nullable=False),
        sa.Column("observed", sa.Double(), nullable=True),
        sa.Column("threshold", sa.Double(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", "rule_id", name="uq_rule_hit"),
    )
    op.create_index("ix_rule_hit_run_fired", "rule_hit", ["run_id", "fired"], unique=False)
    op.create_table(
        "score",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("fused_score", sa.Double(), nullable=False),
        sa.Column("band", sa.CHAR(length=1), nullable=False),
        sa.Column("scorecard_points", sa.Integer(), nullable=False),
        sa.Column("p_scorecard", sa.Double(), nullable=True),
        sa.Column("p_gbm", sa.Double(), nullable=True),
        sa.Column("anomaly_norm", sa.Double(), nullable=True),
        sa.Column("calibrated_probability", sa.Double(), nullable=False),
        sa.Column("calibration_band", sa.String(length=8), nullable=False),
        sa.Column("observed_rate", sa.Double(), nullable=False),
        sa.Column("calibration_n", sa.Integer(), nullable=False),
        sa.Column("predicted_typology", sa.String(length=64), nullable=True),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rule_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.CheckConstraint("band IN ('A','B','C','D','E')", name="ck_score_band"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", name="uq_score_run_key"),
    )
    op.create_index("ix_score_run_band", "score", ["run_id", "band"], unique=False)
    op.create_index(
        "ix_score_run_fused", "score", ["run_id", sa.text("fused_score DESC")], unique=False
    )
    op.create_table(
        "scorecard_attribute",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("attribute", sa.String(length=128), nullable=False),
        sa.Column("iv", sa.Double(), nullable=False),
        sa.Column("n_bins", sa.Integer(), nullable=False),
        sa.Column("monotone", sa.Boolean(), nullable=False),
        sa.Column("family", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "attribute", name="uq_scorecard_attribute"),
    )
    op.create_table(
        "scorecard_bin",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("attribute", sa.String(length=128), nullable=False),
        sa.Column("bin_index", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("woe", sa.Double(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("population_share", sa.Double(), nullable=False),
        sa.Column("bad_rate", sa.Double(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "attribute", "bin_index", name="uq_scorecard_bin"),
    )
    op.create_table(
        "scorecard_point",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("attribute", sa.String(length=128), nullable=False),
        sa.Column("bin_label", sa.String(length=128), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("woe", sa.Double(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("population_share", sa.Double(), nullable=False),
        sa.Column("bad_rate", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", "attribute", name="uq_scorecard_point"),
    )
    op.create_index(
        "ix_scorecard_point_run_key", "scorecard_point", ["run_id", "account_key"], unique=False
    )
    op.create_table(
        "scorecard_spec",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("pdo", sa.Integer(), nullable=False),
        sa.Column("base_score", sa.Integer(), nullable=False),
        sa.Column("base_odds", sa.Double(), nullable=False),
        sa.Column("points_to_double", sa.Double(), nullable=False),
        sa.Column("offset", sa.Double(), nullable=False),
        sa.Column("scale_factor", sa.Double(), nullable=False),
        sa.Column("points_formula", sa.Text(), nullable=False),
        sa.Column("n_total", sa.Integer(), nullable=False),
        sa.Column("n_bad", sa.Integer(), nullable=False),
        sa.Column("fitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "model_version", name="uq_scorecard_spec"),
    )
    op.create_table(
        "shap_contribution",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("feature", sa.String(length=128), nullable=False),
        sa.Column("shap", sa.Double(), nullable=False),
        sa.Column("feature_value", sa.Double(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("evidence_txn_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "account_key", "feature", name="uq_shap_contribution"),
    )
    op.create_index(
        "ix_shap_run_key_rank", "shap_contribution", ["run_id", "account_key", "rank"], unique=False
    )
    op.create_table(
        "stage_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "emitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'complete', 'failed', 'unavailable')",
            name="ck_stage_event_status",
        ),
        sa.CheckConstraint("elapsed_ms >= 0", name="ck_stage_event_elapsed_nonnegative"),
        sa.CheckConstraint("rows >= 0", name="ck_stage_event_rows_nonnegative"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stage_event_run_id_id", "stage_event", ["run_id", "id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("txn_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("event_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_date_local", sa.Date(), nullable=False),
        sa.Column("local_hour", sa.Integer(), nullable=False),
        sa.Column("src_account_key", sa.CHAR(length=12), nullable=True),
        sa.Column("dst_account_key", sa.CHAR(length=12), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("txn_type", sa.String(length=32), nullable=False),
        sa.Column("src_balance_before", sa.BigInteger(), nullable=True),
        sa.Column("src_balance_after", sa.BigInteger(), nullable=True),
        sa.Column("dst_balance_before", sa.BigInteger(), nullable=True),
        sa.Column("dst_balance_after", sa.BigInteger(), nullable=True),
        sa.Column("label_fraud", sa.Boolean(), nullable=True),
        sa.Column("label_typology", sa.String(length=64), nullable=True),
        sa.Column("source_dataset", sa.String(length=64), nullable=False),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name="ck_transaction_currency"),
        sa.CheckConstraint("txn_id ~ '^[a-z0-9_]+:.*'", name="ck_transaction_txn_namespaced"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("txn_id"),
    )
    op.create_index(
        "ix_transaction_dst_ts", "transaction", ["dst_account_key", "event_ts_utc"], unique=False
    )
    op.create_index(
        "ix_transaction_run_ts", "transaction", ["run_id", "event_ts_utc"], unique=False
    )
    op.create_index(
        "ix_transaction_src_ts", "transaction", ["src_account_key", "event_ts_utc"], unique=False
    )
    op.create_table(
        "validation_metric",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("corpus", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("n", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "name", "corpus", name="uq_validation_metric"),
    )
    op.create_table(
        "decision",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("chain_seq", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.CHAR(length=26), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("account_key", sa.CHAR(length=12), nullable=False),
        sa.Column("decision_seq", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("actor_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exposure_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("four_eyes_required", sa.Boolean(), nullable=False),
        sa.Column(
            "four_eyes_state",
            sa.String(length=16),
            server_default=sa.text("'not_required'"),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.String(length=128), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_of_decision_id", sa.String(length=64), nullable=True),
        sa.Column(
            "decided_on_superseded_run",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("case_version_after", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "action IN ('escalate', 'dismiss', 'review', 'reverse')", name="ck_decision_action"
        ),
        sa.CheckConstraint(
            "four_eyes_state <> 'confirmed' OR confirmed_by IS NOT NULL",
            name="ck_decision_confirmer_present",
        ),
        sa.CheckConstraint(
            "four_eyes_state IN ('not_required', 'pending', 'confirmed')",
            name="ck_decision_four_eyes",
        ),
        sa.CheckConstraint("length(btrim(reason)) > 0", name="ck_decision_reason_not_blank"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["review_case.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_decision_id"],
            ["decision.decision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("case_id", "decision_seq", name="uq_decision_case_seq"),
        sa.UniqueConstraint("chain_seq", name="uq_decision_chain_seq"),
    )
    op.create_index("ix_decision_run_key", "decision", ["run_id", "account_key"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("outbox_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.CHAR(length=26), nullable=False),
        sa.Column("case_id", sa.CHAR(length=26), nullable=False),
        sa.Column("decision_seq", sa.Integer(), nullable=False),
        sa.Column("case_seq", sa.Integer(), nullable=False),
        sa.Column("sink_id", sa.String(length=64), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=True),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "attempt_log",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'in_flight', 'sent', 'dead')", name="ck_outbox_status"
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_outbox_attempts"),
        sa.CheckConstraint("max_attempts > 0", name="ck_outbox_max_attempts"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["review_case.case_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.run_id"],
        ),
        sa.PrimaryKeyConstraint("outbox_id"),
        sa.UniqueConstraint("case_id", "case_seq", name="uq_outbox_case_seq"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency"),
    )
    op.create_index("ix_outbox_status_next", "outbox", ["status", "next_attempt_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_status_next", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("ix_decision_run_key", table_name="decision")
    op.drop_table("decision")
    op.drop_table("validation_metric")
    op.drop_index("ix_transaction_src_ts", table_name="transaction")
    op.drop_index("ix_transaction_run_ts", table_name="transaction")
    op.drop_index("ix_transaction_dst_ts", table_name="transaction")
    op.drop_table("transaction")
    op.drop_index("ix_stage_event_run_id_id", table_name="stage_event")
    op.drop_table("stage_event")
    op.drop_index("ix_shap_run_key_rank", table_name="shap_contribution")
    op.drop_table("shap_contribution")
    op.drop_table("scorecard_spec")
    op.drop_index("ix_scorecard_point_run_key", table_name="scorecard_point")
    op.drop_table("scorecard_point")
    op.drop_table("scorecard_bin")
    op.drop_table("scorecard_attribute")
    op.drop_index("ix_score_run_fused", table_name="score")
    op.drop_index("ix_score_run_band", table_name="score")
    op.drop_table("score")
    op.drop_index("ix_rule_hit_run_fired", table_name="rule_hit")
    op.drop_table("rule_hit")
    op.drop_table("review_case")
    op.drop_table("rating_migration")
    op.drop_index("ix_quarantine_run_id", table_name="quarantine_row")
    op.drop_table("quarantine_row")
    op.drop_table("policy_summary")
    op.drop_table("policy_simulation")
    op.drop_index("ix_allocation_run_policy_rank", table_name="policy_allocation")
    op.drop_table("policy_allocation")
    op.drop_table("perturbation_row")
    op.drop_table("model_disagreement")
    op.drop_index("ix_job_run_kind_created", table_name="job_run")
    op.drop_table("job_run")
    op.drop_index("ix_graph_edge_src", table_name="graph_edge")
    op.drop_index("ix_graph_edge_dst", table_name="graph_edge")
    op.drop_table("graph_edge")
    op.drop_table("fairness_row")
    op.drop_index("ix_evidence_run_key_ts", table_name="evidence_event")
    op.drop_table("evidence_event")
    op.drop_index("ix_economics_run_exposure", table_name="economics")
    op.drop_table("economics")
    op.drop_table("drift_period")
    op.drop_table("dataset_file")
    op.drop_table("curve_point")
    op.drop_table("confusion_cell")
    op.drop_table("community")
    op.drop_table("batch")
    op.drop_table("band_definition")
    op.drop_table("backtest_fold")
    op.drop_index("ix_audit_event_subject_seq", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_table("account_membership")
    op.drop_index("ix_account_run_first_seen", table_name="account")
    op.drop_table("account")
    op.drop_table("ablation_row")
    op.drop_table("run")
    op.drop_table("pseudonym_map")
    op.drop_table("policy")
    op.drop_table("measurement")
    op.drop_table("erasure_request")
    op.drop_table("dataset_source")
    # ### end Alembic commands ###
